create table role(
	id bigint generated by default as identity primary key,
	name varchar(50) not null unique
);

create table user_role(
	user_id bigint not null,
	role_id bigint not null,
	primary key (user_id, role_id),
	constraint fk_ur_user foreign key(user_id) references users(id),
	constraint fk_ur_role foreign key(role_id) references role(id)
);

alter table users drop column roles;