create table inventory_item (
    id bigint generated by default as identity primary key,
    product_id bigint not null unique,
    available_quantity int not null,
    version bigint
);

-- seed: product 1 ("Phone") starts with 100 in stock
insert into inventory_item (product_id, available_quantity, version) values (1, 100, 0);