create table stock_reservation (
    id bigint generated by default as identity primary key,
    order_id bigint not null,
    product_id bigint not null,
    quantity int not null,
    status varchar(20) not null,
    -- claim-first idempotency: one reservation per (order, product)
    constraint uq_reservation_order_product unique (order_id, product_id)
);