
    create table audit_log (
        id bigint generated by default as identity,
        action varchar(255) not null,
        primary key (id)
    );

    create table order_item (
        quantity integer not null,
        id bigint generated by default as identity,
        order_id bigint,
        product_id bigint,
        primary key (id)
    );

    create table orders (
        id bigint generated by default as identity,
        customer_name varchar(255),
        primary key (id)
    );

    create table product (
        price float(53) not null,
        id bigint generated by default as identity,
        version bigint,
        name varchar(255) not null unique,
        primary key (id)
    );

    alter table if exists order_item 
       add constraint FKt4dc2r9nbvbujrljv3e23iibt 
       foreign key (order_id) 
       references orders;

    alter table if exists order_item 
       add constraint FK551losx9j75ss5d6bfsqvijna 
       foreign key (product_id) 
       references product;
