
create table outbox (
	id bigint generated by default as identity,
	aggregate_id bigint,
	event_type varchar(255) not null,
	payload clob,
	published boolean not null default false, 
	created_at timestamp not null,
	primary key(id)
);