create table order_status_history(
	id bigint generated by default as identity primary key,
	order_id bigint not null references orders(id),
	from_status varchar(20),
	to_status varchar(20) not null,
	changed_at timestamp not null
);