create table payment(
	id bigint generated by default as identity primary key,
	order_id bigint not null unique,
	amount double precision not null,
	status varchar(20) not null,
	created_at timestamp not null
);