create table review(
	id bigint generated by default as identity primary key,
	product_id bigint not null,
	reviewer_username varchar(255) not null,
	rating int not null,
	comment varchar(2000),
	created_at timestamp not null
);

create table review_image(
	id bigint generated by default as identity primary key,
	review_id bigint not null,
	url varchar(1000) not null,
	constraint fk_image_review foreign key (review_id) references review(id)
);